/**
 * Spec → client types (ADR-016). Renders `openapi/bt-api.v1.json` — the spec S27
 * emits from the route table — into `src/api/generated/`, so the client's payload
 * types are read back out of the published contract instead of trusted to match it.
 *
 * Offline by construction: the spec is read from disk and parsed here, so the
 * generator never resolves a remote `$ref` or fetches anything.
 *
 * `pnpm --filter @bt/web api:types [outDir]` runs this file directly (Node strips the types).
 */
import {
	mkdir, readFile, writeFile,
} from "node:fs/promises";
import {
	dirname, join, resolve,
} from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

// Resolved from the `import.meta.url` string: jsdom (the web test env) swaps in its own `URL` class.
const HERE = dirname(fileURLToPath(import.meta.url));
export const SPEC_PATH = resolve(HERE, "../../../openapi/bt-api.v1.json");
export const GENERATED_DIR = join(HERE, "generated");
export const GENERATED_FILE = "bt-api.v1.ts";

const BANNER = [
	"/* eslint-disable */",
	"// @generated by `pnpm --filter @bt/web api:types` from openapi/bt-api.v1.json — do not edit by hand.",
	"// Regenerate after `pnpm api:spec`; src/api/codegen.test.ts fails while this file is stale.",
	"",
	"",
].join("\n");

export async function renderApiTypes(): Promise<string>
{
	const spec: unknown = JSON.parse(await readFile(SPEC_PATH, "utf8"));
	const ast = await openapiTS(spec as Parameters<typeof openapiTS>[0]);
	return BANNER + astToString(ast);
}

export async function writeApiTypes(outDir: string): Promise<string>
{
	await mkdir(outDir, {
		recursive: true,
	});
	const file = join(outDir, GENERATED_FILE);
	await writeFile(file, await renderApiTypes());
	return file;
}

if (process.argv[1] === fileURLToPath(import.meta.url))
{
	console.log(await writeApiTypes(process.argv[2] ?? GENERATED_DIR));
}
