/**
 * OpenAPI spec for the BT API, generated from the S26 route table (ADR-015).
 *
 * The TypeScript contract stays authoritative: every path comes from walking
 * `ApiRoutes`, and every response schema is generated by `ts-json-schema-generator`
 * from the `<DomainType>Response` alias the table names — never from the bare
 * domain type, so the spec follows the wire type if a `to<DomainType>Response`
 * mapping ever stops being a passthrough. The spec is a derived artifact; nothing
 * here is hand-maintained except what the table cannot carry (status codes,
 * parameters, summaries), which is keyed by `ApiRoute` so a new route fails to
 * typecheck until it is described.
 */
import { fileURLToPath } from "node:url";
import { ApiRoutes } from "@bt/domain";
import type { ApiResponseTypes, ApiRoute } from "@bt/domain";
import { format, resolveConfig } from "prettier";
import { createGenerator } from "ts-json-schema-generator";

type JsonSchema = Record<string, unknown>;

/** The top-level shape `ts-json-schema-generator` returns with `topRef: true`. */
interface GeneratedSchema
{
	$ref?: string;
	definitions?: Record<string, JsonSchema>;
}

/** The error body every 4xx response carries (a name in the route table's registry). */
const ERROR_TYPE: keyof ApiResponseTypes = "ApiErrorResponse";

interface Parameter
{
	name: string;
	in: "path" | "query";
	required: boolean;
	description: string;
	schema: JsonSchema;
}

interface RouteDescription
{
	operationId: string;
	summary: string;
	parameters: Parameter[];
	/** 4xx status → description; each response carries {@link ERROR_TYPE}. Mirrors `handlers/api.ts`. */
	errors: Record<string, string>;
}

const REFRESH: Parameter = {
	name: "refresh",
	in: "query",
	required: false,
	description: "`1` forces an upstream refresh instead of serving the stored copy.",
	schema: {
		type: "string",
		enum: ["1"],
	},
};

/** What the route table cannot carry. Keyed by every route, so adding a route without describing it is a type error. */
export const ROUTE_DESCRIPTIONS: Record<ApiRoute, RouteDescription> = {
	"GET /api/v1/schedule": {
		operationId: "getSchedule",
		summary: "Games scheduled on one day.",
		parameters: [
			{
				name: "date",
				in: "query",
				required: true,
				description: "Day to list, as `YYYY-MM-DD`.",
				schema: {
					type: "string",
					pattern: "^\\d{4}-\\d{2}-\\d{2}$",
				},
			},
			REFRESH,
		],
		errors: {
			400: "`date` is missing or not `YYYY-MM-DD`.",
		},
	},
	"GET /api/v1/games/:gamePk": {
		operationId: "getGame",
		summary: "One game's snapshot, including plays.",
		parameters: [
			{
				name: "gamePk",
				in: "path",
				required: true,
				description: "MLB game id.",
				schema: {
					type: "integer",
				},
			},
			REFRESH,
		],
		errors: {
			404: "No game with that id.",
		},
	},
};

const ROUTE_TYPES_SOURCE = fileURLToPath(new URL("../../../packages/domain/src/api-routes.ts", import.meta.url));
const DOMAIN_TSCONFIG = fileURLToPath(new URL("../../../packages/domain/tsconfig.json", import.meta.url));

/** `/api/v1/games/:gamePk` → `/api/v1/games/{gamePk}`. */
export function toOpenApiPath(path: string): string
{
	return path.replace(/:([A-Za-z0-9_]+)/g, "{$1}");
}

function ref(name: string): JsonSchema
{
	return {
		$ref: `#/components/schemas/${name}`,
	};
}

/** Rewrite JSON Schema `#/definitions/X` refs to OpenAPI component refs, recursively. */
function rewriteRefs(value: unknown): unknown
{
	if (Array.isArray(value))
	{
		return value.map(rewriteRefs);
	}
	if (value !== null && typeof value === "object")
	{
		return Object.fromEntries(Object.entries(value).map(([key, inner]) => [
			key,
			key === "$ref" && typeof inner === "string" ? inner.replace("#/definitions/", "#/components/schemas/") : rewriteRefs(inner),
		]));
	}
	return value;
}

/** Deep copy with object keys sorted, so the emitted file is byte-stable. */
function sortKeys(value: unknown): unknown
{
	if (Array.isArray(value))
	{
		return value.map(sortKeys);
	}
	if (value !== null && typeof value === "object")
	{
		return Object.fromEntries(Object.keys(value).sort().map((key) => [key, sortKeys((value as Record<string, unknown>)[key])]));
	}
	return value;
}

/**
 * Component schemas for each response type name, generated from its declaration.
 * An alias component that the generator resolved to another definition becomes a
 * `$ref` to it, so the spec still names the wire type.
 */
export function generateComponentSchemas(typeNames: readonly (keyof ApiResponseTypes)[]): Record<string, JsonSchema>
{
	const generator = createGenerator({
		path: ROUTE_TYPES_SOURCE,
		tsconfig: DOMAIN_TSCONFIG,
		expose: "export",
		topRef: true,
		skipTypeCheck: true,
	});
	const components: Record<string, JsonSchema> = {};
	for (const name of typeNames)
	{
		const schema = generator.createSchema(name) as GeneratedSchema;
		for (const [defName, definition] of Object.entries(schema.definitions ?? {}))
		{
			components[defName] = rewriteRefs(definition) as JsonSchema;
		}
		const target = schema.$ref?.replace("#/definitions/", "");
		if (target !== undefined && target !== name)
		{
			components[name] = ref(target);
		}
		if (components[name] === undefined)
		{
			throw new Error(`ts-json-schema-generator produced no schema for ${name}`);
		}
	}
	return components;
}

function jsonResponse(description: string, schemaName: string): JsonSchema
{
	return {
		description,
		content: {
			"application/json": {
				schema: ref(schemaName),
			},
		},
	};
}

/** Build the whole document from the route table plus pre-generated component schemas. */
export function buildOpenApiSpec(components: Record<string, JsonSchema>): JsonSchema
{
	const paths: Record<string, Record<string, JsonSchema>> = {};
	for (const [route, responseType] of Object.entries(ApiRoutes) as [ApiRoute, keyof ApiResponseTypes][])
	{
		const [method = "", path = ""] = route.split(" ");
		const description = ROUTE_DESCRIPTIONS[route];
		const responses: Record<string, JsonSchema> = {
			200: jsonResponse("OK", responseType),
		};
		for (const [status, text] of Object.entries(description.errors))
		{
			responses[status] = jsonResponse(text, ERROR_TYPE);
		}
		const openApiPath = toOpenApiPath(path);
		paths[openApiPath] = {
			...paths[openApiPath],
			[method.toLowerCase()]: {
				operationId: description.operationId,
				summary: description.summary,
				parameters: description.parameters,
				responses,
			},
		};
	}
	return sortKeys({
		openapi: "3.1.0",
		info: {
			title: "Baseball Theater API",
			version: "v1",
			description: "Generated from the typed route table in packages/domain/src/api-routes.ts by `pnpm api:spec`. Do not edit by hand.",
		},
		paths,
		components: {
			schemas: components,
		},
	}) as JsonSchema;
}

/** Where the spec is committed; also where Prettier's config is resolved from. */
export const COMMITTED_SPEC = fileURLToPath(new URL("../../../openapi/bt-api.v1.json", import.meta.url));

/**
 * The spec as committed: generated schemas for every type the table and error responses
 * name, formatted with the repo's Prettier config — the pre-commit hook runs Prettier on
 * JSON, so any other formatting would be rewritten on commit and fail the freshness check.
 */
export async function generateOpenApiSpec(): Promise<string>
{
	const typeNames = [...new Set([...Object.values(ApiRoutes), ERROR_TYPE])];
	const json = JSON.stringify(buildOpenApiSpec(generateComponentSchemas(typeNames)));
	return format(json, {
		...await resolveConfig(COMMITTED_SPEC),
		parser: "json",
	});
}
